# Uke 1: Introduksjon til vitenskapelig Python

I denne notebooken går vi gjennom grunnleggende funksjoner i **NumPy**, et nøkkelbibliotek for å gjøre numeriske beregninger i Python.

Etter å ha jobba dere gjennom denne veiledningen, vil dere ha lært:
- Hvordan NumPy-arrayer fungerer (og hvordan de er forskjellige fra Python-lister)
- Hvordan man oppretter og kombinerer arrayer
- Hvordan man bruker kringkasting (eng: *broadcasting*), indeksering og aggregering
- Hvorfor NumPy er **mye raskere** enn ren Python


In [1]:
# Importing libraries:
import numpy as np

## Opprette arrayer og inspisere dem
I NumPy er et `array` kjernedatastrukturen.  
Disse kan vi tenke på som ordnede lister, men i motsetning til vanlige Python-lister er matriser homogene: alle elementene må ha samme datatype (`dtype`). 

Internt lagrer NumPy matriseelementer i sammenhengende minneblokker, noe som muliggjør operasjoner implementert i kodespråket C, som er raskere enn de samme operasjonene i Python.

La oss opprette våre første arrayer!

In [2]:
# Creating Numpy arrays:
# 1D array 
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:\n", arr_1d)

# 2D array 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array:\n", arr_2d)

# 3D array 
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr_3d)

1D array:
 [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Nå som vi har noen arrays, skal vi se nærmere på egenskapene deres.

Alle arrays du oppretter med NumPy er av typen `numpy.ndarray`. 
Dette er de viktigste nøkkelegenskapene til denne typen:

- `.shape`: angir størrelsen på arrayen langs hver akse.
- `.ndim`: antall dimensjoner (akser) arrayen har.
- `.dtype`: typen data som er lagret i arrayen (f.eks. int32, float64). Alle elementer har samme dtype.
- `.T`: transponeringen av arrayen (rader blir kolonner, kolonner blir rader).


In [3]:
# Checking the type of the arrays
print(type(arr_1d))  # Output: <class 'numpy.ndarray'>
print(type(arr_2d))  # Output: <class 'numpy.ndarray'>

# Shape of the arrays
print("Shape of 1D array:", arr_1d.shape)  # Output: (5,)
print("Shape of 2D array:", arr_2d.shape)  # Output: (3, 3)
print("Shape of 3D array:", arr_3d.shape)  # Output: (2, 2, 2)

# Number of dimensions (ndim) of the arrays
print("Dimensions of 1D array:", arr_1d.ndim)  # Output: 1
print("Dimensions of 2D array:", arr_2d.ndim)  # Output: 2
print("Dimensions of 3D array:", arr_3d.ndim)  # Output: 3

# Data type of elements (dtype)
print("Data type of 1D array:", arr_1d.dtype) # Output: int64 (or int32 depending on your system)
print("Data type of 2D array:", arr_2d.dtype) # Output: int64 (or int32 depending on your system)
print("Data type of 3D array:", arr_3d.dtype) # Output: int64 (or int32 depending on your system)

# Transpose of a 2D array (rows <-> columns)
print("Original 2D array:\n", arr_2d) 
print("Transposed 2D array:\n", arr_2d.T)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Shape of 1D array: (5,)
Shape of 2D array: (3, 3)
Shape of 3D array: (2, 2, 2)
Dimensions of 1D array: 1
Dimensions of 2D array: 2
Dimensions of 3D array: 3
Data type of 1D array: int64
Data type of 2D array: int64
Data type of 3D array: int64
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed 2D array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Man kan også endre formen på en array ved hjelp av `.reshape()`.

In [4]:
# Reshaping arrays
arr_reshaped = arr_1d.reshape((5, 1))  # Reshape to 5 rows, 1 column
print("Reshaped 1D array to 2D (5,1):\n", arr_reshaped)

arr_reshaped_2 = arr_2d.reshape((1, 9))  # Reshape to 1 row, 9 columns
print("Reshaped 2D array to 1D (1,9):\n", arr_reshaped_2)

arr_reshaped_3 = arr_2d.reshape((9, 1))  # Reshape to 9 rows, 1 column
print("Reshaped 2D array to 2D (9,1):\n", arr_reshaped_3)

Reshaped 1D array to 2D (5,1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
Reshaped 2D array to 1D (1,9):
 [[1 2 3 4 5 6 7 8 9]]
Reshaped 2D array to 2D (9,1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Transponering fungerer også for høyere dimensjoner, men i er enklest å se i 2D: formen (rader, kolonner) blir formen (kolonner, rader).

## Indeksering og slicing

På samme måte som med Python-lister, kan hente og endre enkeltelementer eller deler av en array ved hjelp av indeksering og slicing, men NumPy har kraftigere funksjoner for flerdimensjonale matriser.


In [5]:
# Accessing elements in a 1D array
print("Element at index 2 in 1D array:", arr_1d[2])  # Output: 3

# Accessing elements in a 2D array
print("Element at row 1, col 2 in 2D array:", arr_2d[1, 2])  # Output: 6

# Slicing 1D array
print("Slicing 1D array [1:4]:", arr_1d[1:4])  # Output: [2, 3, 4]

# Slicing 2D array
print("Slicing 2D array [0:2, 1:3]:\n", arr_2d[0:2, 1:3])

Element at index 2 in 1D array: 3
Element at row 1, col 2 in 2D array: 6
Slicing 1D array [1:4]: [2 3 4]
Slicing 2D array [0:2, 1:3]:
 [[2 3]
 [5 6]]


## Vektoriserte operasjoner vs. Python-løkker

I stedet for å iterere gjennom individuelle elementer i Python, utfører NumPy operasjoner på større datablokker i parallell, ved hjelp av optimaliserte lavnivåoperasjoner. Dette eliminerer overheaden til Python-løkker og lar beregningene kjøre mye nærmere hastigheten til kompilert C-kode.


In [6]:
# Basic operations on Numpy arrays:
# Element-wise addition
arr_sum = arr_1d + 2  # Adds 2 to each element
print("1D array after addition:\n", arr_sum)

# Element-wise multiplication
arr_product = arr_2d * 2  # Multiplies each element by 2
print("2D array after multiplication:\n", arr_product)

# Element-wise multiplication between arrays (same shape)
arr_elementwise = arr_2d * arr_2d  # Multiplies corresponding elements
print("Element-wise array multiplication:\n", arr_elementwise)

# Matrix multiplication
arr_mult = np.dot(arr_2d, arr_2d)  # 2D matrix multiplication
print("Matrix multiplication result:\n", arr_mult)

1D array after addition:
 [3 4 5 6 7]
2D array after multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Element-wise array multiplication:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Matrix multiplication result:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Her sammenligner vi en ren Python-løkke med et vektorisert NumPy-uttrykk:


In [7]:
# Vectorization
arr = np.array([1, 2, 3, 4, 5])

# Without vectorization (using a Python loop)
squared = np.zeros_like(arr)

for i in range(len(arr)):
    squared[i] = arr[i] ** 2

print(squared)  # Output: [ 1  4  9 16 25]

# With vectorization (using NumPy's array operations)
squared_vectorized = arr ** 2
print(squared_vectorized)  # Output: [ 1  4  9 16 25]

[ 1  4  9 16 25]
[ 1  4  9 16 25]


La oss nå måle ytelsesforskjellen mellom en ren Python og NumPy ved hjelp av "magikommandoen" `%timeit` i Jupyter.

In [8]:
large = np.random.rand(2_000_000)

# Pure Python loop
def py_loop(xs):
    out = []
    append = out.append
    for x in xs:
        append(x * 1.234 + 2.0)
    return out

%timeit py_loop(large)

# Vectorized NumPy
%timeit large * 1.234 + 2.0

215 ms ± 6.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.27 ms ± 132 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Broadcasting

Broadcasting tillater å gjøre operasjoner på arrays med forskjellige, men kompatible former.
Når vi opererer på to arrays, sammenligner NumPy formene deres med utgangspunkt i den *siste dimensjonen* og utvider automatisk alle dimensjoner med størrelse 1 for å matche størrelsen på den andre matrisen.
Dette gjør at matriser med forskjellige former kan fungere sammen så lenge hver dimensjon enten matcher eller har størrelse 1.


In [ ]:
# Array Broadcasting:
# Broadcasting a scalar to a 2D array
# The scalar 10 is broadcast to match the shape of arr_2d.
# The addition happens element-wise across the whole array. This is a vectorized operation.
print("2D array before broadcasting addition:\n", arr_2d)
arr_broadcast = arr_2d + 10
print("2D array after broadcasting addition:\n", arr_broadcast)

# Broadcasting a 1D array to a 2D array
# arr_1d[:3] = [1, 2, 3] is broadcast across each row of arr_2d.
# Again, the operation is vectorized (applied to all elements without explicit loops).
arr_2d_broadcast = arr_2d + arr_1d[:3]  # arr_1d[:3] = [1, 2, 3]
print("Broadcasted 2D array:\n", arr_2d_broadcast)

2D array before broadcasting addition:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2D array after broadcasting addition:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Broadcasted 2D array:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## Array-konstruktører

NumPy tilbyr noen funksjoner for å opprette arrays med spesifikke verdier eller mønstre, noe som kan være svært nyttig for å initialisere datastrukturer.


In [10]:
# Creating Arrays with Special Functions
# Array of zeros
arr_zeros = np.zeros((3, 3))
print("Array of zeros:\n", arr_zeros)

# Array of ones
arr_ones = np.ones((2, 2))
print("Array of ones:\n", arr_ones)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1.]
 [1. 1.]]


In [11]:
# Array of evenly spaced values (like a range)
arr_range = np.arange(0, 10, 2)
print("Array with range 0 to 10 with step 2:", arr_range)

# Array of random values
arr_random = np.random.random((2, 3))
print("Array of random values:\n", arr_random)

Array with range 0 to 10 with step 2: [0 2 4 6 8]
Array of random values:
 [[0.04277098 0.04304958 0.88666725]
 [0.58645821 0.91017757 0.43147615]]


## Tilfeldige tall i NumPy

For å generere tilfeldige tall bruker vi typisk `np.random`, som har en rekke funksjoner som lar deg trekke tall fra forskjellige fordelinger.

Vi setter ofte et **seed** for å sikre at resultatene er reproduserbare.  
Dette betyr at hver gang du kjører koden, vil du få de samme tilfeldige tallene.

In [12]:
# Setting a seed for reproducibility
np.random.seed(42)

# Array of 5 random floats between 0 and 1
x = np.random.rand(5)
print(x)

# Array of 5 random integers between 0 and 9
y = np.random.randint(0, 10, 5)
print(y)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[2 6 7 4 3]


## Kombinere arrays

Vi kan kombinere arrays ved hjelp av funksjoner som `np.vstack` (vertikal stabling) og `np.hstack` (horisontal stabling).
Husk at arrayene må ha kompatible former for at disse operasjonene skal fungere.


In [13]:
# Combining Arrays
# Stacking arrays vertically
arr_vstack = np.vstack((arr_1d, arr_1d))
print("Vertically stacked array:\n", arr_vstack)

# Stacking arrays horizontally
arr_hstack = np.hstack((arr_1d, arr_1d))
print("Horizontally stacked array:\n", arr_hstack)

Vertically stacked array:
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Horizontally stacked array:
 [1 2 3 4 5 1 2 3 4 5]


## Aggregeringer og reduksjoner

NumPy tilbyr mange innebygde funksjoner for å beregne sammendragsstatistikk og utføre reduksjoner på matriser.
Funksjoner som `sum()`, `mean()`, `std()`, `min()`, `max()` osv. kan operere langs en **akse**.
Bruk argumentet `axis` for å velge om NumPy skal redusere over rader vs. kolonner.


In [14]:
# Numpy functions for numerical analysis
arr = np.array([1, 2, 3, 4, 5])

print("Mean of the 1D array:", np.mean(arr))  # Output: 3.0
print("Standard deviation of the 1D array:", np.std(arr))   # Output: 1.414...
print("Sum of all elements in the 1D array:", np.sum(arr))   # Output: 15
print("Maximum value in the 1D array:", np.max(arr))   # Output: 5

# 2D example with axis argument
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# axis=0 → operate down columns
print("Mean along columns (axis=0):", np.mean(arr_2d, axis=0)) # Output: [2.5 3.5 4.5]
# axis=1 → operate across rows
print("Sum along rows (axis=1):", np.sum(arr_2d, axis=1)) # Output: [ 6 15]
# Overall operations (no axis)
print("Overall max:", np.max(arr_2d)) # Output: 6

Mean of the 1D array: 3.0
Standard deviation of the 1D array: 1.4142135623730951
Sum of all elements in the 1D array: 15
Maximum value in the 1D array: 5
Mean along columns (axis=0): [2.5 3.5 4.5]
Sum along rows (axis=1): [ 6 15]
Overall max: 6


In [15]:
# Vectorization
# Without vectorization (using a Python loop)
arr = np.array([1, 2, 3, 4, 5])
squared = np.zeros_like(arr)

for i in range(len(arr)):
    squared[i] = arr[i] ** 2

print(squared)  # Output: [ 1  4  9 16 25]

# With vectorization (using NumPy's array operations)
squared_vectorized = arr ** 2
print(squared_vectorized)  # Output: [ 1  4  9 16 25]

[ 1  4  9 16 25]
[ 1  4  9 16 25]


## Øvingsoppgaver

I disse oppgavene kan dere øve dere på å bruke konseptene vi har gått gjennom:

### Oppgave 1: Broadcasting og vektorisering
- Opprett en array $A$ med verdiene 1 til 15, omformet til formen (5, 3).
- Opprett en radvektor $v = [10, 0, -10]$ og en kolonnevektor $r = [[1],[2],[3],[4],[5]]$.

Uten bruk av Python-løkker:
-  Legg $v$ til hver rad i $A$ ved hjelp av broadcasting.
-  Multipliser hver rad i resultatet med $r$.
-  Beregn gjennomsnitt for kolonnene (akse=0) og summer radene (akse=1) for den endelige matrisen.


In [16]:
# You can write your code here for Exercise 1



### Oppgave 2: Manipulering av NumPy-arrays

- Lag en 1D-array $B$ som inneholder verdier fra 1 til 16.
- Omform $B$ til formen (4, 4).
- Transponer den omformede matrisen.
- Stable den omformede $B$ og dens transponerte versjon vertikalt.
- Beregn summen av alle elementene i den stablede matrisen.
- Finn maksimumsverdien i hver rad i den stablede matrisen.
- Finn indeksen til minimumsverdien i hver kolonne i den stablede matrisen.


In [17]:
# You can write your code here for Exercise 2



### Øvelse 3: NumPy-matrisekonstruktører og tilfeldige tall

- Lag en 3x3-matrise med nuller.
- Lag en 2x4-matrise med enere.
- Lag en 1D-array med verdier fra 5 til 25 med trinn på 5.
- Lag en 4x4-matrise med tilfeldige desimaltall mellom 0 og 1.
- Lag en 3x3-matrise med tilfeldige heltall mellom 1 og 10.
- Sett en tilfeldig startverdi til 123 og generer en 1D-matrise med 10 tilfeldige desimaltall mellom 0 og 1. Gjenta genereringen for å bekrefte reproduserbarheten.


In [18]:
# You can write your code here for Exercise 3

